export const SKILL_CATALOG = {
  frontend: [
    ["JavaScript", ["javascript", "java script"]],
    ["TypeScript", ["typescript", "type script"]],
    ["React", ["react", "reactjs", "react js"]],
    ["Next.js", ["next.js", "next js", "nextjs"]],
    ["Angular", ["angular", "angularjs", "angular js"]],
    ["Vue.js", ["vue", "vue.js", "vuejs", "vue js"]],
    ["Svelte", ["svelte", "sveltekit", "svelte kit"]],
    ["HTML", ["html", "html5"]],
    ["CSS", ["css", "css3"]],
    ["Sass", ["sass", "scss"]],
    ["Tailwind CSS", ["tailwind", "tailwindcss", "tailwind css"]],
    ["Bootstrap", ["bootstrap"]],
    ["Redux", ["redux", "redux toolkit"]],
    ["Webpack", ["webpack"]],
    ["Vite", ["vite"]],
    ["Figma", ["figma"]],
  ],
  backend: [
    ["Node.js", ["node.js", "node js", "nodejs"]],
    ["Express", ["express", "expressjs", "express js"]],
    ["NestJS", ["nestjs", "nest js"]],
    ["Python", ["python"]],
    ["Django", ["django"]],
    ["Flask", ["flask"]],
    ["FastAPI", ["fastapi", "fast api"]],
    ["Java", ["java"]],
    ["Spring Boot", ["spring boot", "springboot"]],
    ["C#", ["c#", "c sharp"]],
    [".NET", [".net", "dotnet", "dot net", "asp.net", "asp net"]],
    ["C++", ["c++", "cpp", "c plus plus"]],
    ["PHP", ["php"]],
    ["Laravel", ["laravel"]],
    ["Ruby", ["ruby"]],
    ["Ruby on Rails", ["ruby on rails", "rails"]],
    ["Go", ["golang", "go language"]],
    ["Rust", ["rust"]],
  ],
  databases: [
    ["SQL", ["sql"]],
    ["MySQL", ["mysql", "my sql"]],
    ["PostgreSQL", ["postgresql", "postgres", "postgre sql"]],
    ["Microsoft SQL Server", ["sql server", "mssql", "ms sql"]],
    ["Oracle Database", ["oracle database", "oracle db"]],
    ["MongoDB", ["mongodb", "mongo db", "mongo"]],
    ["Redis", ["redis"]],
    ["Elasticsearch", ["elasticsearch", "elastic search", "elastic"]],
    ["Firebase", ["firebase"]],
    ["DynamoDB", ["dynamodb", "dynamo db"]],
    ["Cassandra", ["cassandra"]],
    ["SQLite", ["sqlite", "sqlite3"]],
  ],
  cloud: [
    ["AWS", ["aws", "amazon web services"]],
    ["Amazon S3", ["amazon s3", "aws s3", "s3"]],
    ["AWS Lambda", ["aws lambda", "lambda functions"]],
    ["Azure", ["azure", "microsoft azure"]],
    ["Google Cloud", ["gcp", "google cloud", "google cloud platform"]],
    ["Cloudflare", ["cloudflare", "cloud flare"]],
    ["Heroku", ["heroku"]],
    ["Vercel", ["vercel"]],
    ["Netlify", ["netlify"]],
  ],
  devops: [
    ["Docker", ["docker", "containerization"]],
    ["Kubernetes", ["kubernetes", "k8s"]],
    ["Terraform", ["terraform"]],
    ["Ansible", ["ansible"]],
    ["Jenkins", ["jenkins"]],
    ["GitHub Actions", ["github actions", "github workflows"]],
    ["GitLab CI", ["gitlab ci", "gitlab pipelines"]],
    ["CI/CD", ["ci/cd", "ci cd", "continuous integration", "continuous delivery"]],
    ["Linux", ["linux", "unix"]],
    ["Nginx", ["nginx", "engine x"]],
    ["Apache", ["apache", "apache http server"]],
    ["Prometheus", ["prometheus"]],
    ["Grafana", ["grafana"]],
  ],
  cybersecurity: [
    ["Cybersecurity", ["cybersecurity", "cyber security", "information security"]],
    ["Application Security", ["application security", "appsec", "app sec"]],
    ["OWASP", ["owasp"]],
    ["Penetration Testing", ["penetration testing", "pen testing", "pentesting"]],
    ["Network Security", ["network security"]],
    ["SIEM", ["siem", "security information and event management"]],
    ["OAuth", ["oauth", "oauth2", "oauth 2"]],
    ["JWT", ["jwt", "json web token"]],
    ["Encryption", ["encryption", "cryptography"]],
  ],
  aiMl: [
    ["Machine Learning", ["machine learning", "ml"]],
    ["Artificial Intelligence", ["artificial intelligence", "ai"]],
    ["Deep Learning", ["deep learning"]],
    ["Natural Language Processing", ["natural language processing", "nlp"]],
    ["Computer Vision", ["computer vision"]],
    ["TensorFlow", ["tensorflow", "tensor flow"]],
    ["PyTorch", ["pytorch", "py torch"]],
    ["scikit-learn", ["scikit-learn", "scikit learn", "sklearn"]],
    ["Pandas", ["pandas"]],
    ["NumPy", ["numpy", "num py"]],
    ["LLMs", ["llm", "llms", "large language model", "large language models"]],
    ["MLOps", ["mlops", "ml ops"]],
  ],
  mobile: [
    ["React Native", ["react native", "reactnative"]],
    ["Flutter", ["flutter"]],
    ["Dart", ["dart"]],
    ["Android", ["android"]],
    ["iOS", ["ios", "iphone os"]],
    ["Swift", ["swift"]],
    ["Kotlin", ["kotlin"]],
    ["Xcode", ["xcode"]],
  ],
  testing: [
    ["Jest", ["jest"]],
    ["React Testing Library", ["react testing library", "testing library"]],
    ["Cypress", ["cypress"]],
    ["Playwright", ["playwright"]],
    ["Selenium", ["selenium"]],
    ["Mocha", ["mocha"]],
    ["Chai", ["chai"]],
    ["JUnit", ["junit"]],
    ["Pytest", ["pytest", "py test"]],
    ["Postman", ["postman"]],
    ["Unit Testing", ["unit testing", "unit tests"]],
    ["Integration Testing", ["integration testing", "integration tests"]],
  ],
  versionControl: [
    ["Git", ["git"]],
    ["GitHub", ["github"]],
    ["GitLab", ["gitlab"]],
    ["Bitbucket", ["bitbucket"]],
  ],
  operatingSystems: [
    ["Windows", ["windows"]],
    ["macOS", ["macos", "mac os", "os x"]],
    ["Ubuntu", ["ubuntu"]],
    ["Bash", ["bash", "shell scripting", "shell script"]],
    ["PowerShell", ["powershell", "power shell"]],
  ],
  apis: [
    ["REST APIs", ["rest api", "rest apis", "restful api", "restful apis"]],
    ["GraphQL", ["graphql", "graph ql"]],
    ["SOAP", ["soap", "soap api"]],
    ["gRPC", ["grpc", "g rpc"]],
    ["WebSockets", ["websocket", "websockets", "web socket"]],
    ["Microservices", ["microservices", "microservice architecture"]],
    ["API Integration", ["api integration", "third party api"]],
  ],
  softSkills: [
    ["Communication", ["communication", "written communication", "verbal communication"]],
    ["Teamwork", ["teamwork", "team player", "collaboration"]],
    ["Leadership", ["leadership", "team leadership"]],
    ["Problem Solving", ["problem solving", "problem-solving"]],
    ["Time Management", ["time management"]],
    ["Adaptability", ["adaptability", "adaptable"]],
    ["Critical Thinking", ["critical thinking"]],
    ["Agile", ["agile", "scrum"]],
  ],
};
